name: Deploy to Hosting

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WP_DOMAIN: ${{ vars.WP_DOMAIN}}
    steps:
      - name: Use variables
        env:
          WP_DOMAIN: ${{ vars.WP_DOMAIN }}
        run: |
          echo "variable from shell environment : ${{ vars.WP_DOMAIN }}"
          echo "WP_DOMAIN=$WP_DOMAIN" >> $GITHUB_ENV
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v4

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
